spring:
  datasource:
    url: jdbc:mysql://n1nlmysql45plsk.secureserver.net:3306/daniil_ph19997519606
    username: daniil_admin
    password: D86w%70sm
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
  thymeleaf:
    prefix: classpath:/templates/
  mail:
    host: smtp.gmail.com
    port: 587
    username: daniil.rain.open@gmail.com
    password: pmhmhojhfwhpwqcc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    org.springframework: Error



paypal:
  mode: sandbox
  client:
    id: ASdeLcpEtBVvBiJtS6woBT9xZ3WaTY8aRywe7bPuyimJt-RcxT7fHuYwnpKIIdlhRQw4a_jQtwdncNp2
    secret: EBDWYdJQCiX-dV1UgZohbzFuBIdB-g8J6qwjkUfeNz4PjUVbS-DmAAYIW-4ibPmQYxEkTLKH9vI3AsQ4
